-- Content expansion: Minefield only ever shipped with whatever content was
-- seeded directly in the database, so rooms were repeating questions
-- quickly. Adds 30 new questions (10 easy / 10 medium / 10 hard) spread
-- across a wide mix of categories, each with a 9-tile board
-- (easy = 6 safe / 3 mines, medium = 5 safe / 4 mines, hard = 3 safe / 6 mines).

insert into minefield_questions
  (category_en, category_de, question_en, question_de,
   correct_answers_en, correct_answers_de, wrong_answers_en, wrong_answers_de, difficulty)
values
  -- Easy
  ('Geography', 'Geografie',
    'Which of these are capital cities in Europe?', 'Welche davon sind europäische Hauptstädte?',
    ARRAY['Paris','Berlin','Madrid','Rome','Lisbon','Vienna'],
    ARRAY['Paris','Berlin','Madrid','Rom','Lissabon','Wien'],
    ARRAY['Sydney','Tokyo','Cairo'],
    ARRAY['Sydney','Tokio','Kairo'], 'easy'),

  ('Science', 'Wissenschaft',
    'Which of these are planets in our solar system?', 'Welche davon sind Planeten unseres Sonnensystems?',
    ARRAY['Mars','Venus','Jupiter','Saturn','Earth','Neptune'],
    ARRAY['Mars','Venus','Jupiter','Saturn','Erde','Neptun'],
    ARRAY['Pluto','The Sun','The Moon'],
    ARRAY['Pluto','Die Sonne','Der Mond'], 'easy'),

  ('Animals', 'Tiere',
    'Which of these are dog breeds?', 'Welche davon sind Hunderassen?',
    ARRAY['Labrador','Poodle','Beagle','Boxer','Dachshund','Chihuahua'],
    ARRAY['Labrador','Pudel','Beagle','Boxer','Dackel','Chihuahua'],
    ARRAY['Persian cat','Siamese cat','Canary'],
    ARRAY['Perserkatze','Siamkatze','Kanarienvogel'], 'easy'),

  ('Movies & TV', 'Filme & TV',
    'Which of these are Pixar movies?', 'Welche davon sind Pixar-Filme?',
    ARRAY['Up','Coco','Cars','Brave','Ratatouille','Inside Out'],
    ARRAY['Oben','Coco','Cars','Merida','Ratatouille','Alles steht Kopf'],
    ARRAY['Shrek','Frozen','Minions'],
    ARRAY['Shrek','Die Eiskönigin','Minions'], 'easy'),

  ('Sports', 'Sport',
    'Which of these are Olympic sports?', 'Welche davon sind olympische Sportarten?',
    ARRAY['Swimming','Athletics','Gymnastics','Cycling','Rowing','Fencing'],
    ARRAY['Schwimmen','Leichtathletik','Turnen','Radfahren','Rudern','Fechten'],
    ARRAY['Chess','Poker','Darts'],
    ARRAY['Schach','Poker','Darts'], 'easy'),

  ('Food', 'Essen',
    'Which of these are fruits?', 'Welche davon sind Früchte?',
    ARRAY['Apple','Banana','Mango','Cherry','Kiwi','Grape'],
    ARRAY['Apfel','Banane','Mango','Kirsche','Kiwi','Traube'],
    ARRAY['Carrot','Potato','Broccoli'],
    ARRAY['Karotte','Kartoffel','Brokkoli'], 'easy'),

  ('General', 'Allgemein',
    'Which of these colors appear in a rainbow?', 'Welche dieser Farben erscheinen in einem Regenbogen?',
    ARRAY['Red','Orange','Yellow','Green','Blue','Violet'],
    ARRAY['Rot','Orange','Gelb','Grün','Blau','Violett'],
    ARRAY['Black','White','Brown'],
    ARRAY['Schwarz','Weiß','Braun'], 'easy'),

  ('Geography', 'Geografie',
    'Which of these are Nordic countries or territories?', 'Welche davon sind nordische Länder oder Gebiete?',
    ARRAY['Sweden','Norway','Denmark','Finland','Iceland','Greenland'],
    ARRAY['Schweden','Norwegen','Dänemark','Finnland','Island','Grönland'],
    ARRAY['Germany','Poland','Netherlands'],
    ARRAY['Deutschland','Polen','Niederlande'], 'easy'),

  ('Games', 'Spiele',
    'Which of these are card games?', 'Welche davon sind Kartenspiele?',
    ARRAY['Poker','Blackjack','Bridge','Skat','Rummy','Solitaire'],
    ARRAY['Poker','Blackjack','Bridge','Skat','Rommé','Solitär'],
    ARRAY['Chess','Monopoly','Twister'],
    ARRAY['Schach','Monopoly','Twister'], 'easy'),

  ('Science', 'Wissenschaft',
    'Which of these are organs in the human body?', 'Welche davon sind Organe im menschlichen Körper?',
    ARRAY['Heart','Liver','Lungs','Kidney','Brain','Stomach'],
    ARRAY['Herz','Leber','Lunge','Niere','Gehirn','Magen'],
    ARRAY['Femur','Bicep','Cartilage'],
    ARRAY['Oberschenkelknochen','Bizeps','Knorpel'], 'easy'),

  -- Medium
  ('Geography', 'Geografie',
    'Which of these countries are in Asia?', 'Welche dieser Länder liegen in Asien?',
    ARRAY['Japan','Thailand','Vietnam','India','Mongolia'],
    ARRAY['Japan','Thailand','Vietnam','Indien','Mongolei'],
    ARRAY['Egypt','Kenya','Peru','Morocco'],
    ARRAY['Ägypten','Kenia','Peru','Marokko'], 'medium'),

  ('Sports', 'Sport',
    'Which of these terms are used in tennis?', 'Welche dieser Begriffe werden im Tennis verwendet?',
    ARRAY['Love','Deuce','Ace','Fault','Break'],
    ARRAY['Love','Deuce','Ass','Fehler','Break'],
    ARRAY['Strike','Offside','Touchdown','Dribble'],
    ARRAY['Strike','Abseits','Touchdown','Dribbling'], 'medium'),

  ('Food', 'Essen',
    'Which of these are types of cheese?', 'Welche davon sind Käsesorten?',
    ARRAY['Gouda','Cheddar','Feta','Mozzarella','Brie'],
    ARRAY['Gouda','Cheddar','Feta','Mozzarella','Brie'],
    ARRAY['Yogurt','Butter','Cream','Milk'],
    ARRAY['Joghurt','Butter','Sahne','Milch'], 'medium'),

  ('History', 'Geschichte',
    'Which of these have been Presidents of the United States?', 'Welche davon waren Präsidenten der Vereinigten Staaten?',
    ARRAY['Abraham Lincoln','George Washington','Barack Obama','John F. Kennedy','Theodore Roosevelt'],
    ARRAY['Abraham Lincoln','George Washington','Barack Obama','John F. Kennedy','Theodore Roosevelt'],
    ARRAY['Winston Churchill','Nelson Mandela','Margaret Thatcher','Charles de Gaulle'],
    ARRAY['Winston Churchill','Nelson Mandela','Margaret Thatcher','Charles de Gaulle'], 'medium'),

  ('Music', 'Musik',
    'Which of these are string instruments?', 'Welche davon sind Streichinstrumente?',
    ARRAY['Violin','Cello','Viola','Double Bass','Harp'],
    ARRAY['Geige','Cello','Bratsche','Kontrabass','Harfe'],
    ARRAY['Flute','Trumpet','Drums','Clarinet'],
    ARRAY['Flöte','Trompete','Schlagzeug','Klarinette'], 'medium'),

  ('Geography', 'Geografie',
    'Which of these are currencies still used today?', 'Welche davon sind Währungen, die heute noch verwendet werden?',
    ARRAY['Yen','Peso','Rupee','Won','Krona'],
    ARRAY['Yen','Peso','Rupie','Won','Krone'],
    ARRAY['Deutsche Mark','French Franc','Italian Lira','Dutch Guilder'],
    ARRAY['Deutsche Mark','Französischer Franc','Italienische Lira','Niederländischer Gulden'], 'medium'),

  ('Geography', 'Geografie',
    'Which of these countries share a border with Germany?', 'Welche dieser Länder grenzen an Deutschland?',
    ARRAY['France','Poland','Austria','Switzerland','Netherlands'],
    ARRAY['Frankreich','Polen','Österreich','Schweiz','Niederlande'],
    ARRAY['Italy','Spain','Hungary','Portugal'],
    ARRAY['Italien','Spanien','Ungarn','Portugal'], 'medium'),

  ('Movies & TV', 'Filme & TV',
    'Which of these superheroes originate from Marvel Comics?', 'Welche dieser Superhelden stammen aus Marvel Comics?',
    ARRAY['Spider-Man','Iron Man','Thor','Black Panther','Captain America'],
    ARRAY['Spider-Man','Iron Man','Thor','Black Panther','Captain America'],
    ARRAY['Batman','Superman','Wonder Woman','Aquaman'],
    ARRAY['Batman','Superman','Wonder Woman','Aquaman'], 'medium'),

  ('Geography', 'Geografie',
    'Which of these countries are in Africa?', 'Welche dieser Länder liegen in Afrika?',
    ARRAY['Nigeria','Kenya','Egypt','Morocco','Ghana'],
    ARRAY['Nigeria','Kenia','Ägypten','Marokko','Ghana'],
    ARRAY['Jordan','Lebanon','Nepal','Colombia'],
    ARRAY['Jordanien','Libanon','Nepal','Kolumbien'], 'medium'),

  ('Games', 'Spiele',
    'Which of these are board games?', 'Welche davon sind Brettspiele?',
    ARRAY['Monopoly','Chess','Risk','Catan','Scrabble'],
    ARRAY['Monopoly','Schach','Risiko','Catan','Scrabble'],
    ARRAY['Poker','Uno','Solitaire','Charades'],
    ARRAY['Poker','Uno','Solitär','Scharade'], 'medium'),

  -- Hard
  ('Science', 'Wissenschaft',
    'Which of these are real chemical elements?', 'Welche davon sind echte chemische Elemente?',
    ARRAY['Xenon','Osmium','Tungsten'],
    ARRAY['Xenon','Osmium','Wolfram'],
    ARRAY['Adamantium','Kryptonite','Vibranium','Unobtainium','Mithril','Dilithium'],
    ARRAY['Adamantium','Kryptonit','Vibranium','Unobtainium','Mithril','Dilithium'], 'hard'),

  ('Animals', 'Tiere',
    'Which of these animals are marsupials?', 'Welche dieser Tiere sind Beuteltiere?',
    ARRAY['Kangaroo','Koala','Wombat'],
    ARRAY['Känguru','Koala','Wombat'],
    ARRAY['Platypus','Armadillo','Anteater','Sloth','Hedgehog','Otter'],
    ARRAY['Schnabeltier','Gürteltier','Ameisenbär','Faultier','Igel','Otter'], 'hard'),

  ('Movies & TV', 'Filme & TV',
    'Which of these actors have played Batman in a live-action film?', 'Welche dieser Schauspieler haben Batman in einem Realfilm gespielt?',
    ARRAY['Christian Bale','Michael Keaton','Robert Pattinson'],
    ARRAY['Christian Bale','Michael Keaton','Robert Pattinson'],
    ARRAY['Tobey Maguire','Henry Cavill','Chris Evans','Ryan Reynolds','Hugh Jackman','Tom Holland'],
    ARRAY['Tobey Maguire','Henry Cavill','Chris Evans','Ryan Reynolds','Hugh Jackman','Tom Holland'], 'hard'),

  ('History', 'Geschichte',
    'Which of these were Roman Emperors?', 'Welche davon waren römische Kaiser?',
    ARRAY['Augustus','Nero','Trajan'],
    ARRAY['Augustus','Nero','Trajan'],
    ARRAY['Hannibal','Spartacus','Pericles','Alexander the Great','Leonidas','Socrates'],
    ARRAY['Hannibal','Spartacus','Perikles','Alexander der Große','Leonidas','Sokrates'], 'hard'),

  ('Literature', 'Literatur',
    'Which of these are plays written by William Shakespeare?', 'Welche davon sind Theaterstücke von William Shakespeare?',
    ARRAY['Hamlet','Macbeth','Othello'],
    ARRAY['Hamlet','Macbeth','Othello'],
    ARRAY['Faust','Doctor Faustus','The Canterbury Tales','Don Quixote','Antigone','A Doll''s House'],
    ARRAY['Faust','Doktor Faustus','Die Canterbury-Erzählungen','Don Quijote','Antigone','Ein Puppenheim'], 'hard'),

  ('Science', 'Wissenschaft',
    'Which of these elements are gases at room temperature?', 'Welche dieser Elemente sind bei Raumtemperatur gasförmig?',
    ARRAY['Helium','Neon','Nitrogen'],
    ARRAY['Helium','Neon','Stickstoff'],
    ARRAY['Mercury','Bromine','Iron','Sodium','Calcium','Sulfur'],
    ARRAY['Quecksilber','Brom','Eisen','Natrium','Kalzium','Schwefel'], 'hard'),

  ('Mythology', 'Mythologie',
    'Which of these are gods from Greek mythology?', 'Welche davon sind Götter aus der griechischen Mythologie?',
    ARRAY['Zeus','Athena','Poseidon'],
    ARRAY['Zeus','Athene','Poseidon'],
    ARRAY['Thor','Odin','Ra','Anubis','Osiris','Loki'],
    ARRAY['Thor','Odin','Ra','Anubis','Osiris','Loki'], 'hard'),

  ('Geography', 'Geografie',
    'Which of these countries are landlocked (no coastline)?', 'Welche dieser Länder sind Binnenländer (ohne Meereszugang)?',
    ARRAY['Switzerland','Austria','Mongolia'],
    ARRAY['Schweiz','Österreich','Mongolei'],
    ARRAY['Spain','Italy','Portugal','Greece','Norway','Brazil'],
    ARRAY['Spanien','Italien','Portugal','Griechenland','Norwegen','Brasilien'], 'hard'),

  ('Science', 'Wissenschaft',
    'Which of these are official Nobel Prize categories?', 'Welche davon sind offizielle Nobelpreis-Kategorien?',
    ARRAY['Physics','Chemistry','Literature'],
    ARRAY['Physik','Chemie','Literatur'],
    ARRAY['Mathematics','Biology','Sports','Art','Music','Architecture'],
    ARRAY['Mathematik','Biologie','Sport','Kunst','Musik','Architektur'], 'hard'),

  ('Animals', 'Tiere',
    'Which of these snakes are venomous?', 'Welche dieser Schlangen sind giftig?',
    ARRAY['King Cobra','Black Mamba','Rattlesnake'],
    ARRAY['Königskobra','Schwarze Mamba','Klapperschlange'],
    ARRAY['Boa Constrictor','Python','Anaconda','Garter Snake','Corn Snake','Milk Snake'],
    ARRAY['Abgottschlange','Python','Anakonda','Strumpfbandnatter','Kornnatter','Königsnatter'], 'hard');
