-- Content expansion: 90 more Minefield questions (30 easy / 30 medium /
-- 30 hard), covering topics not used by the previous content migration, so
-- rooms take much longer to see a repeat. Board sizing follows the same
-- convention as before: easy = 6 safe / 3 mines, medium = 5 safe / 4 mines,
-- hard = 3 safe / 6 mines, all on a 9-tile board.

insert into minefield_questions
  (category_en, category_de, question_en, question_de,
   correct_answers_en, correct_answers_de, wrong_answers_en, wrong_answers_de, difficulty)
values
  -- Easy
  ('Nature', 'Natur',
    'Which of these are types of trees?', 'Welche davon sind Baumarten?',
    ARRAY['Oak','Pine','Maple','Birch','Willow','Cedar'],
    ARRAY['Eiche','Kiefer','Ahorn','Birke','Weide','Zeder'],
    ARRAY['Rose','Tulip','Daisy'],
    ARRAY['Rose','Tulpe','Gänseblümchen'], 'easy'),

  ('Animals', 'Tiere',
    'Which of these are farm animals?', 'Welche davon sind Nutztiere?',
    ARRAY['Cow','Pig','Sheep','Chicken','Horse','Goat'],
    ARRAY['Kuh','Schwein','Schaf','Huhn','Pferd','Ziege'],
    ARRAY['Lion','Tiger','Elephant'],
    ARRAY['Löwe','Tiger','Elefant'], 'easy'),

  ('Food', 'Essen',
    'Which of these are vegetables?', 'Welche davon sind Gemüsesorten?',
    ARRAY['Carrot','Potato','Onion','Cucumber','Spinach','Pepper'],
    ARRAY['Karotte','Kartoffel','Zwiebel','Gurke','Spinat','Paprika'],
    ARRAY['Apple','Banana','Orange'],
    ARRAY['Apfel','Banane','Orange'], 'easy'),

  ('Geography', 'Geografie',
    'Which of these are continents?', 'Welche davon sind Kontinente?',
    ARRAY['Africa','Asia','Europe','North America','South America','Australia'],
    ARRAY['Afrika','Asien','Europa','Nordamerika','Südamerika','Australien'],
    ARRAY['Greenland','The Sahara','The Amazon Rainforest'],
    ARRAY['Grönland','Die Sahara','Der Amazonas-Regenwald'], 'easy'),

  ('Sports', 'Sport',
    'Which of these are winter sports?', 'Welche davon sind Wintersportarten?',
    ARRAY['Skiing','Ice Hockey','Snowboarding','Figure Skating','Curling','Bobsled'],
    ARRAY['Skifahren','Eishockey','Snowboarden','Eiskunstlauf','Curling','Bobfahren'],
    ARRAY['Surfing','Volleyball','Golf'],
    ARRAY['Surfen','Volleyball','Golf'], 'easy'),

  ('Movies & TV', 'Filme & TV',
    'Which of these are Disney animated movies?', 'Welche davon sind Disney-Animationsfilme?',
    ARRAY['Frozen','Aladdin','Mulan','Tangled','Moana','Encanto'],
    ARRAY['Die Eiskönigin','Aladdin','Mulan','Rapunzel','Vaiana','Encanto'],
    ARRAY['Shrek','Rio','Sing'],
    ARRAY['Shrek','Rio','Sing'], 'easy'),

  ('General', 'Allgemein',
    'Which of these are days of the week?', 'Welche davon sind Wochentage?',
    ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
    ARRAY['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'],
    ARRAY['January','Spring','Morning'],
    ARRAY['Januar','Frühling','Morgen'], 'easy'),

  ('Music', 'Musik',
    'Which of these are music genres?', 'Welche davon sind Musikgenres?',
    ARRAY['Jazz','Rock','Pop','Reggae','Hip Hop','Classical'],
    ARRAY['Jazz','Rock','Pop','Reggae','Hip-Hop','Klassik'],
    ARRAY['Sculpture','Painting','Poetry'],
    ARRAY['Skulptur','Malerei','Poesie'], 'easy'),

  ('Sports', 'Sport',
    'Which of these sports are played with a ball?', 'Welche dieser Sportarten werden mit einem Ball gespielt?',
    ARRAY['Soccer','Basketball','Tennis','Baseball','Volleyball','Golf'],
    ARRAY['Fußball','Basketball','Tennis','Baseball','Volleyball','Golf'],
    ARRAY['Swimming','Running','Boxing'],
    ARRAY['Schwimmen','Laufen','Boxen'], 'easy'),

  ('Food', 'Essen',
    'Which of these are breakfast foods?', 'Welche davon sind Frühstücksgerichte?',
    ARRAY['Eggs','Toast','Pancakes','Cereal','Bacon','Oatmeal'],
    ARRAY['Eier','Toast','Pfannkuchen','Müsli','Speck','Haferbrei'],
    ARRAY['Steak','Soup','Pizza'],
    ARRAY['Steak','Suppe','Pizza'], 'easy'),

  ('Animals', 'Tiere',
    'Which of these are birds?', 'Welche davon sind Vögel?',
    ARRAY['Eagle','Parrot','Penguin','Owl','Sparrow','Flamingo'],
    ARRAY['Adler','Papagei','Pinguin','Eule','Spatz','Flamingo'],
    ARRAY['Bat','Butterfly','Dragonfly'],
    ARRAY['Fledermaus','Schmetterling','Libelle'], 'easy'),

  ('Geography', 'Geografie',
    'Which of these countries are in South America?', 'Welche dieser Länder liegen in Südamerika?',
    ARRAY['Brazil','Argentina','Chile','Peru','Colombia','Ecuador'],
    ARRAY['Brasilien','Argentinien','Chile','Peru','Kolumbien','Ecuador'],
    ARRAY['Mexico','Spain','Portugal'],
    ARRAY['Mexiko','Spanien','Portugal'], 'easy'),

  ('Science', 'Wissenschaft',
    'Which of these are simple machines?', 'Welche davon sind einfache Maschinen?',
    ARRAY['Lever','Pulley','Wheel','Screw','Wedge','Inclined Plane'],
    ARRAY['Hebel','Flaschenzug','Rad','Schraube','Keil','Schiefe Ebene'],
    ARRAY['Engine','Battery','Computer'],
    ARRAY['Motor','Batterie','Computer'], 'easy'),

  ('Games', 'Spiele',
    'Which of these are video game consoles?', 'Welche davon sind Videospielkonsolen?',
    ARRAY['PlayStation','Xbox','Nintendo Switch','Wii','GameCube','Sega Genesis'],
    ARRAY['PlayStation','Xbox','Nintendo Switch','Wii','GameCube','Sega Genesis'],
    ARRAY['iPhone','Laptop','Television'],
    ARRAY['iPhone','Laptop','Fernseher'], 'easy'),

  ('General', 'Allgemein',
    'Which of these months have 31 days?', 'Welche dieser Monate haben 31 Tage?',
    ARRAY['January','March','May','July','August','December'],
    ARRAY['Januar','März','Mai','Juli','August','Dezember'],
    ARRAY['April','June','November'],
    ARRAY['April','Juni','November'], 'easy'),

  ('Food', 'Essen',
    'Which of these are tree nuts?', 'Welche davon sind Baumnüsse?',
    ARRAY['Almond','Walnut','Cashew','Pistachio','Hazelnut','Pecan'],
    ARRAY['Mandel','Walnuss','Cashew','Pistazie','Haselnuss','Pekannuss'],
    ARRAY['Lentil','Pea','Bean'],
    ARRAY['Linse','Erbse','Bohne'], 'easy'),

  ('Animals', 'Tiere',
    'Which of these live in the ocean?', 'Welche davon leben im Ozean?',
    ARRAY['Dolphin','Shark','Octopus','Jellyfish','Starfish','Crab'],
    ARRAY['Delfin','Hai','Oktopus','Qualle','Seestern','Krabbe'],
    ARRAY['Frog','Duck','Beaver'],
    ARRAY['Frosch','Ente','Biber'], 'easy'),

  ('Geography', 'Geografie',
    'Which of these are famous rivers?', 'Welche davon sind berühmte Flüsse?',
    ARRAY['The Nile','The Amazon','The Mississippi','The Danube','The Rhine','The Thames'],
    ARRAY['Der Nil','Der Amazonas','Der Mississippi','Die Donau','Der Rhein','Die Themse'],
    ARRAY['The Sahara','Mount Everest','The Atlantic Ocean'],
    ARRAY['Die Sahara','Der Mount Everest','Der Atlantik'], 'easy'),

  ('Movies & TV', 'Filme & TV',
    'Which of these are characters from Harry Potter?', 'Welche davon sind Charaktere aus Harry Potter?',
    ARRAY['Harry Potter','Hermione Granger','Ron Weasley','Albus Dumbledore','Severus Snape','Draco Malfoy'],
    ARRAY['Harry Potter','Hermine Granger','Ron Weasley','Albus Dumbledore','Severus Snape','Draco Malfoy'],
    ARRAY['Frodo Baggins','Luke Skywalker','Percy Jackson'],
    ARRAY['Frodo Beutlin','Luke Skywalker','Percy Jackson'], 'easy'),

  ('Sports', 'Sport',
    'Which of these are martial arts?', 'Welche davon sind Kampfsportarten?',
    ARRAY['Karate','Judo','Taekwondo','Boxing','Kickboxing','Wrestling'],
    ARRAY['Karate','Judo','Taekwondo','Boxen','Kickboxen','Ringen'],
    ARRAY['Yoga','Pilates','Gymnastics'],
    ARRAY['Yoga','Pilates','Turnen'], 'easy'),

  ('Science', 'Wissenschaft',
    'Which of these are insects?', 'Welche davon sind Insekten?',
    ARRAY['Ant','Bee','Butterfly','Beetle','Grasshopper','Ladybug'],
    ARRAY['Ameise','Biene','Schmetterling','Käfer','Heuschrecke','Marienkäfer'],
    ARRAY['Spider','Scorpion','Tick'],
    ARRAY['Spinne','Skorpion','Zecke'], 'easy'),

  ('Geography', 'Geografie',
    'Which of these are deserts?', 'Welche davon sind Wüsten?',
    ARRAY['The Sahara','The Gobi','The Kalahari','The Mojave','The Atacama','The Sonoran Desert'],
    ARRAY['Die Sahara','Die Gobi','Die Kalahari','Die Mojave-Wüste','Die Atacama','Die Sonora-Wüste'],
    ARRAY['The Amazon Rainforest','Mount Everest','The Nile Delta'],
    ARRAY['Der Amazonas-Regenwald','Der Mount Everest','Das Nildelta'], 'easy'),

  ('Food', 'Essen',
    'Which of these are desserts?', 'Welche davon sind Nachspeisen?',
    ARRAY['Cake','Ice Cream','Pudding','Cookies','Brownies','Donuts'],
    ARRAY['Kuchen','Eis','Pudding','Kekse','Brownies','Donuts'],
    ARRAY['Salad','Soup','Sandwich'],
    ARRAY['Salat','Suppe','Sandwich'], 'easy'),

  ('Music', 'Musik',
    'Which of these are percussion instruments?', 'Welche davon sind Schlaginstrumente?',
    ARRAY['Drums','Xylophone','Tambourine','Cymbals','Maracas','Bongo'],
    ARRAY['Schlagzeug','Xylophon','Tamburin','Becken','Maracas','Bongo'],
    ARRAY['Flute','Guitar','Violin'],
    ARRAY['Flöte','Gitarre','Geige'], 'easy'),

  ('Animals', 'Tiere',
    'Which of these are big cats?', 'Welche davon sind Großkatzen?',
    ARRAY['Lion','Tiger','Leopard','Cheetah','Jaguar','Cougar'],
    ARRAY['Löwe','Tiger','Leopard','Gepard','Jaguar','Puma'],
    ARRAY['Wolf','Fox','Hyena'],
    ARRAY['Wolf','Fuchs','Hyäne'], 'easy'),

  ('Geography', 'Geografie',
    'Which of these are U.S. states?', 'Welche davon sind US-Bundesstaaten?',
    ARRAY['California','Texas','Florida','New York','Nevada','Alaska'],
    ARRAY['Kalifornien','Texas','Florida','New York','Nevada','Alaska'],
    ARRAY['Toronto','Paris','London'],
    ARRAY['Toronto','Paris','London'], 'easy'),

  ('General', 'Allgemein',
    'Which of these shapes have only straight sides?', 'Welche dieser Formen haben nur gerade Seiten?',
    ARRAY['Square','Triangle','Rectangle','Pentagon','Hexagon','Rhombus'],
    ARRAY['Quadrat','Dreieck','Rechteck','Fünfeck','Sechseck','Raute'],
    ARRAY['Circle','Oval','Sphere'],
    ARRAY['Kreis','Oval','Kugel'], 'easy'),

  ('Movies & TV', 'Filme & TV',
    'Which of these are famous cartoon characters?', 'Welche davon sind berühmte Zeichentrickfiguren?',
    ARRAY['Mickey Mouse','SpongeBob SquarePants','Bugs Bunny','Tom and Jerry','Homer Simpson','Scooby-Doo'],
    ARRAY['Mickey Mouse','SpongeBob Schwammkopf','Bugs Bunny','Tom und Jerry','Homer Simpson','Scooby-Doo'],
    ARRAY['Batman','Sherlock Holmes','James Bond'],
    ARRAY['Batman','Sherlock Holmes','James Bond'], 'easy'),

  ('Food', 'Essen',
    'Which of these are common pizza toppings?', 'Welche davon sind gängige Pizzabeläge?',
    ARRAY['Pepperoni','Mushroom','Onion','Olives','Ham','Pineapple'],
    ARRAY['Salami','Pilze','Zwiebeln','Oliven','Schinken','Ananas'],
    ARRAY['Chocolate','Ice Cream','Cereal'],
    ARRAY['Schokolade','Eis','Müsli'], 'easy'),

  ('Geography', 'Geografie',
    'Which of these are famous mountains?', 'Welche davon sind berühmte Berge?',
    ARRAY['Mount Everest','Kilimanjaro','K2','Matterhorn','Mount Fuji','Denali'],
    ARRAY['Mount Everest','Kilimandscharo','K2','Matterhorn','Fuji','Denali'],
    ARRAY['The Amazon River','The Sahara Desert','The Pacific Ocean'],
    ARRAY['Der Amazonas','Die Sahara','Der Pazifik'], 'easy'),

  -- Medium
  ('Geography', 'Geografie',
    'Which of these are capital cities in South America?', 'Welche davon sind südamerikanische Hauptstädte?',
    ARRAY['Buenos Aires','Santiago','Lima','Bogotá','Brasília'],
    ARRAY['Buenos Aires','Santiago','Lima','Bogotá','Brasília'],
    ARRAY['Madrid','Lisbon','Toronto','Ottawa'],
    ARRAY['Madrid','Lissabon','Toronto','Ottawa'], 'medium'),

  ('Science', 'Wissenschaft',
    'Which of these are noble gases?', 'Welche davon sind Edelgase?',
    ARRAY['Helium','Neon','Argon','Krypton','Xenon'],
    ARRAY['Helium','Neon','Argon','Krypton','Xenon'],
    ARRAY['Oxygen','Nitrogen','Hydrogen','Chlorine'],
    ARRAY['Sauerstoff','Stickstoff','Wasserstoff','Chlor'], 'medium'),

  ('History', 'Geschichte',
    'Which of these events happened in the 20th century?', 'Welche dieser Ereignisse fanden im 20. Jahrhundert statt?',
    ARRAY['The Moon Landing','World War II','The Fall of the Berlin Wall','The Invention of Television','The Wright Brothers'' First Flight'],
    ARRAY['Die Mondlandung','Der Zweite Weltkrieg','Der Fall der Berliner Mauer','Die Erfindung des Fernsehers','Der erste Flug der Gebrüder Wright'],
    ARRAY['The French Revolution','The Signing of the Magna Carta','The Building of the Pyramids','The Fall of the Roman Empire'],
    ARRAY['Die Französische Revolution','Die Unterzeichnung der Magna Carta','Der Bau der Pyramiden','Der Untergang des Römischen Reiches'], 'medium'),

  ('Movies & TV', 'Filme & TV',
    'Which of these actors have played James Bond?', 'Welche dieser Schauspieler haben James Bond gespielt?',
    ARRAY['Sean Connery','Roger Moore','Pierce Brosnan','Daniel Craig','Timothy Dalton'],
    ARRAY['Sean Connery','Roger Moore','Pierce Brosnan','Daniel Craig','Timothy Dalton'],
    ARRAY['Tom Cruise','Matt Damon','Liam Neeson','Jason Statham'],
    ARRAY['Tom Cruise','Matt Damon','Liam Neeson','Jason Statham'], 'medium'),

  ('Geography', 'Geografie',
    'Which of these countries are islands?', 'Welche dieser Länder sind Inseln?',
    ARRAY['Japan','Iceland','Madagascar','Sri Lanka','Cuba'],
    ARRAY['Japan','Island','Madagaskar','Sri Lanka','Kuba'],
    ARRAY['Egypt','France','Germany','Thailand'],
    ARRAY['Ägypten','Frankreich','Deutschland','Thailand'], 'medium'),

  ('Food', 'Essen',
    'Which of these are types of pasta?', 'Welche davon sind Nudelsorten?',
    ARRAY['Spaghetti','Penne','Fusilli','Lasagna','Ravioli'],
    ARRAY['Spaghetti','Penne','Fusilli','Lasagne','Ravioli'],
    ARRAY['Sushi','Tacos','Falafel','Croissant'],
    ARRAY['Sushi','Tacos','Falafel','Croissant'], 'medium'),

  ('Science', 'Wissenschaft',
    'Which of these are real vitamins?', 'Welche davon sind echte Vitamine?',
    ARRAY['Vitamin A','Vitamin B','Vitamin C','Vitamin D','Vitamin E'],
    ARRAY['Vitamin A','Vitamin B','Vitamin C','Vitamin D','Vitamin E'],
    ARRAY['Vitamin F','Vitamin G','Vitamin J','Vitamin L'],
    ARRAY['Vitamin F','Vitamin G','Vitamin J','Vitamin L'], 'medium'),

  ('Sports', 'Sport',
    'Which of these are racket sports?', 'Welche davon sind Schlägersportarten?',
    ARRAY['Tennis','Badminton','Squash','Table Tennis','Racquetball'],
    ARRAY['Tennis','Badminton','Squash','Tischtennis','Racquetball'],
    ARRAY['Golf','Cricket','Baseball','Fencing'],
    ARRAY['Golf','Cricket','Baseball','Fechten'], 'medium'),

  ('Geography', 'Geografie',
    'Which of these countries share a border with France?', 'Welche dieser Länder grenzen an Frankreich?',
    ARRAY['Spain','Germany','Italy','Belgium','Switzerland'],
    ARRAY['Spanien','Deutschland','Italien','Belgien','Schweiz'],
    ARRAY['Portugal','Austria','Netherlands','Poland'],
    ARRAY['Portugal','Österreich','Niederlande','Polen'], 'medium'),

  ('Movies & TV', 'Filme & TV',
    'Which of these are Studio Ghibli films?', 'Welche davon sind Studio-Ghibli-Filme?',
    ARRAY['Spirited Away','My Neighbor Totoro','Princess Mononoke','Howl''s Moving Castle','Ponyo'],
    ARRAY['Chihiros Reise ins Zauberland','Mein Nachbar Totoro','Prinzessin Mononoke','Das wandelnde Schloss','Ponyo'],
    ARRAY['Toy Story','Finding Nemo','Frozen','Shrek'],
    ARRAY['Toy Story','Findet Nemo','Die Eiskönigin','Shrek'], 'medium'),

  ('History', 'Geschichte',
    'Which of these are famous explorers?', 'Welche davon sind berühmte Entdecker?',
    ARRAY['Christopher Columbus','Marco Polo','Ferdinand Magellan','Vasco da Gama','James Cook'],
    ARRAY['Christoph Kolumbus','Marco Polo','Ferdinand Magellan','Vasco da Gama','James Cook'],
    ARRAY['Isaac Newton','Albert Einstein','Charles Darwin','Nikola Tesla'],
    ARRAY['Isaac Newton','Albert Einstein','Charles Darwin','Nikola Tesla'], 'medium'),

  ('Science', 'Wissenschaft',
    'Which of these are dinosaurs?', 'Welche davon sind Dinosaurier?',
    ARRAY['Tyrannosaurus','Triceratops','Velociraptor','Stegosaurus','Brachiosaurus'],
    ARRAY['Tyrannosaurus','Triceratops','Velociraptor','Stegosaurus','Brachiosaurus'],
    ARRAY['Woolly Mammoth','Saber-Toothed Tiger','Dodo','Pterodactyl'],
    ARRAY['Wollhaarmammut','Säbelzahntiger','Dodo','Flugsaurier'], 'medium'),

  ('Geography', 'Geografie',
    'Which of these countries use the Euro?', 'Welche dieser Länder verwenden den Euro?',
    ARRAY['Germany','France','Italy','Spain','Netherlands'],
    ARRAY['Deutschland','Frankreich','Italien','Spanien','Niederlande'],
    ARRAY['Switzerland','United Kingdom','Sweden','Poland'],
    ARRAY['Schweiz','Vereinigtes Königreich','Schweden','Polen'], 'medium'),

  ('Food', 'Essen',
    'Which of these are herbs or spices?', 'Welche davon sind Kräuter oder Gewürze?',
    ARRAY['Basil','Oregano','Cinnamon','Paprika','Thyme'],
    ARRAY['Basilikum','Oregano','Zimt','Paprika','Thymian'],
    ARRAY['Spinach','Lettuce','Cabbage','Broccoli'],
    ARRAY['Spinat','Salat','Kohl','Brokkoli'], 'medium'),

  ('Sports', 'Sport',
    'Which of these are combat sports at the Olympics?', 'Welche davon sind Kampfsportarten bei den Olympischen Spielen?',
    ARRAY['Boxing','Judo','Taekwondo','Wrestling','Fencing'],
    ARRAY['Boxen','Judo','Taekwondo','Ringen','Fechten'],
    ARRAY['Archery','Rowing','Swimming','Gymnastics'],
    ARRAY['Bogenschießen','Rudern','Schwimmen','Turnen'], 'medium'),

  ('Geography', 'Geografie',
    'Which of these countries are in the Caribbean?', 'Welche dieser Länder liegen in der Karibik?',
    ARRAY['Cuba','Jamaica','Haiti','Dominican Republic','Bahamas'],
    ARRAY['Kuba','Jamaika','Haiti','Dominikanische Republik','Bahamas'],
    ARRAY['Costa Rica','Panama','Belize','Mexico'],
    ARRAY['Costa Rica','Panama','Belize','Mexiko'], 'medium'),

  ('Science', 'Wissenschaft',
    'Which of these are among the five classic human senses?', 'Welche davon zählen zu den fünf klassischen menschlichen Sinnen?',
    ARRAY['Sight','Hearing','Smell','Taste','Touch'],
    ARRAY['Sehen','Hören','Riechen','Schmecken','Tasten'],
    ARRAY['Balance','Intuition','Hunger','Thirst'],
    ARRAY['Gleichgewicht','Intuition','Hunger','Durst'], 'medium'),

  ('Music', 'Musik',
    'Which of these are famous composers?', 'Welche davon sind berühmte Komponisten?',
    ARRAY['Mozart','Beethoven','Bach','Chopin','Tchaikovsky'],
    ARRAY['Mozart','Beethoven','Bach','Chopin','Tschaikowski'],
    ARRAY['Picasso','Shakespeare','Einstein','Da Vinci'],
    ARRAY['Picasso','Shakespeare','Einstein','Da Vinci'], 'medium'),

  ('Geography', 'Geografie',
    'Which of these countries are monarchies today?', 'Welche dieser Länder sind heute Monarchien?',
    ARRAY['United Kingdom','Japan','Spain','Sweden','Netherlands'],
    ARRAY['Vereinigtes Königreich','Japan','Spanien','Schweden','Niederlande'],
    ARRAY['France','Germany','USA','Italy'],
    ARRAY['Frankreich','Deutschland','USA','Italien'], 'medium'),

  ('Food', 'Essen',
    'Which of these are citrus fruits?', 'Welche davon sind Zitrusfrüchte?',
    ARRAY['Orange','Lemon','Lime','Grapefruit','Mandarin'],
    ARRAY['Orange','Zitrone','Limette','Grapefruit','Mandarine'],
    ARRAY['Apple','Peach','Plum','Pear'],
    ARRAY['Apfel','Pfirsich','Pflaume','Birne'], 'medium'),

  ('History', 'Geschichte',
    'Which of these were among the Seven Wonders of the Ancient World?', 'Welche davon zählten zu den Sieben Weltwundern der Antike?',
    ARRAY['The Great Pyramid of Giza','The Hanging Gardens of Babylon','The Colossus of Rhodes','The Lighthouse of Alexandria','The Statue of Zeus'],
    ARRAY['Die Große Pyramide von Gizeh','Die Hängenden Gärten von Babylon','Der Koloss von Rhodos','Der Leuchtturm von Alexandria','Die Statue des Zeus'],
    ARRAY['The Eiffel Tower','The Great Wall of China','The Taj Mahal','The Colosseum'],
    ARRAY['Der Eiffelturm','Die Chinesische Mauer','Der Taj Mahal','Das Kolosseum'], 'medium'),

  ('Geography', 'Geografie',
    'Which of these countries are in Central America?', 'Welche dieser Länder liegen in Mittelamerika?',
    ARRAY['Guatemala','Honduras','Nicaragua','Panama','Costa Rica'],
    ARRAY['Guatemala','Honduras','Nicaragua','Panama','Costa Rica'],
    ARRAY['Colombia','Venezuela','Cuba','Ecuador'],
    ARRAY['Kolumbien','Venezuela','Kuba','Ecuador'], 'medium'),

  ('Science', 'Wissenschaft',
    'Which of these are types of clouds?', 'Welche davon sind Wolkenarten?',
    ARRAY['Cumulus','Stratus','Cirrus','Nimbus','Cumulonimbus'],
    ARRAY['Cumulus','Stratus','Cirrus','Nimbus','Cumulonimbus'],
    ARRAY['Tornado','Hurricane','Blizzard','Drought'],
    ARRAY['Tornado','Hurrikan','Blizzard','Dürre'], 'medium'),

  ('Sports', 'Sport',
    'Which of these sports are part of the Winter Olympics?', 'Welche dieser Sportarten gehören zu den Olympischen Winterspielen?',
    ARRAY['Ski Jumping','Speed Skating','Luge','Biathlon','Curling'],
    ARRAY['Skispringen','Eisschnelllauf','Rodeln','Biathlon','Curling'],
    ARRAY['Surfing','Beach Volleyball','Marathon','Triathlon'],
    ARRAY['Surfen','Beachvolleyball','Marathon','Triathlon'], 'medium'),

  ('Geography', 'Geografie',
    'Which of these countries border the Mediterranean Sea?', 'Welche dieser Länder grenzen an das Mittelmeer?',
    ARRAY['Spain','Italy','Greece','Turkey','Egypt'],
    ARRAY['Spanien','Italien','Griechenland','Türkei','Ägypten'],
    ARRAY['Germany','Poland','Sweden','Austria'],
    ARRAY['Deutschland','Polen','Schweden','Österreich'], 'medium'),

  ('Food', 'Essen',
    'Which of these are types of tea?', 'Welche davon sind Teesorten?',
    ARRAY['Green Tea','Black Tea','Oolong','Chamomile','Peppermint'],
    ARRAY['Grüner Tee','Schwarzer Tee','Oolong','Kamillentee','Pfefferminztee'],
    ARRAY['Espresso','Cappuccino','Latte','Cocoa'],
    ARRAY['Espresso','Cappuccino','Latte Macchiato','Kakao'], 'medium'),

  ('Movies & TV', 'Filme & TV',
    'Which of these are animated TV shows?', 'Welche davon sind Zeichentrickserien?',
    ARRAY['SpongeBob SquarePants','The Simpsons','Rick and Morty','Adventure Time','Family Guy'],
    ARRAY['SpongeBob Schwammkopf','Die Simpsons','Rick and Morty','Adventure Time','Family Guy'],
    ARRAY['Friends','Breaking Bad','Stranger Things','The Office'],
    ARRAY['Friends','Breaking Bad','Stranger Things','The Office'], 'medium'),

  ('Geography', 'Geografie',
    'Which of these countries share a border with Russia?', 'Welche dieser Länder grenzen an Russland?',
    ARRAY['China','Mongolia','Kazakhstan','Finland','Ukraine'],
    ARRAY['China','Mongolei','Kasachstan','Finnland','Ukraine'],
    ARRAY['Germany','France','Spain','Italy'],
    ARRAY['Deutschland','Frankreich','Spanien','Italien'], 'medium'),

  ('Science', 'Wissenschaft',
    'Which of these are parts of a plant?', 'Welche davon sind Pflanzenteile?',
    ARRAY['Root','Stem','Leaf','Flower','Seed'],
    ARRAY['Wurzel','Stängel','Blatt','Blüte','Samen'],
    ARRAY['Fur','Feather','Scale','Shell'],
    ARRAY['Fell','Feder','Schuppe','Schale'], 'medium'),

  ('History', 'Geschichte',
    'Which of these countries were major powers in World War I?', 'Welche dieser Länder waren im Ersten Weltkrieg Großmächte?',
    ARRAY['Germany','France','Britain','Russia','Austria-Hungary'],
    ARRAY['Deutschland','Frankreich','Großbritannien','Russland','Österreich-Ungarn'],
    ARRAY['Spain','Switzerland','Sweden','Norway'],
    ARRAY['Spanien','Schweiz','Schweden','Norwegen'], 'medium'),

  -- Hard
  ('Movies & TV', 'Filme & TV',
    'Which of these actors have played Spider-Man in a live-action film?', 'Welche dieser Schauspieler haben Spider-Man in einem Realfilm gespielt?',
    ARRAY['Tobey Maguire','Andrew Garfield','Tom Holland'],
    ARRAY['Tobey Maguire','Andrew Garfield','Tom Holland'],
    ARRAY['Christian Bale','Henry Cavill','Ryan Reynolds','Chris Hemsworth','Chris Evans','Robert Downey Jr.'],
    ARRAY['Christian Bale','Henry Cavill','Ryan Reynolds','Chris Hemsworth','Chris Evans','Robert Downey Jr.'], 'hard'),

  ('Science', 'Wissenschaft',
    'Which of these elements are radioactive?', 'Welche dieser Elemente sind radioaktiv?',
    ARRAY['Uranium','Plutonium','Radium'],
    ARRAY['Uran','Plutonium','Radium'],
    ARRAY['Gold','Silver','Iron','Copper','Titanium','Aluminum'],
    ARRAY['Gold','Silber','Eisen','Kupfer','Titan','Aluminium'], 'hard'),

  ('History', 'Geschichte',
    'Which of these were ancient Egyptian pharaohs?', 'Welche davon waren altägyptische Pharaonen?',
    ARRAY['Tutankhamun','Ramesses II','Cleopatra'],
    ARRAY['Tutanchamun','Ramses II.','Kleopatra'],
    ARRAY['Hammurabi','Nebuchadnezzar','Darius','Xerxes','Genghis Khan','Attila the Hun'],
    ARRAY['Hammurabi','Nebukadnezar','Dareios','Xerxes','Dschingis Khan','Attila der Hunne'], 'hard'),

  ('Mythology', 'Mythologie',
    'Which of these are gods from Norse mythology?', 'Welche davon sind Götter aus der nordischen Mythologie?',
    ARRAY['Odin','Thor','Loki'],
    ARRAY['Odin','Thor','Loki'],
    ARRAY['Zeus','Ra','Osiris','Vishnu','Jupiter','Apollo'],
    ARRAY['Zeus','Ra','Osiris','Vishnu','Jupiter','Apollo'], 'hard'),

  ('Geography', 'Geografie',
    'Which of these are among the world''s three smallest sovereign states?', 'Welche davon zählen zu den drei kleinsten souveränen Staaten der Welt?',
    ARRAY['Vatican City','Monaco','San Marino'],
    ARRAY['Vatikanstadt','Monaco','San Marino'],
    ARRAY['Liechtenstein','Malta','Luxembourg','Andorra','Cyprus','Slovenia'],
    ARRAY['Liechtenstein','Malta','Luxemburg','Andorra','Zypern','Slowenien'], 'hard'),

  ('Literature', 'Literatur',
    'Which of these novels were written by Fyodor Dostoevsky?', 'Welche dieser Romane wurden von Fjodor Dostojewski geschrieben?',
    ARRAY['Crime and Punishment','The Brothers Karamazov','The Idiot'],
    ARRAY['Schuld und Sühne','Die Brüder Karamasow','Der Idiot'],
    ARRAY['War and Peace','Anna Karenina','Animal Farm','1984','The Great Gatsby','Moby Dick'],
    ARRAY['Krieg und Frieden','Anna Karenina','Farm der Tiere','1984','Der große Gatsby','Moby Dick'], 'hard'),

  ('Science', 'Wissenschaft',
    'Which of these are fundamental forces of nature?', 'Welche davon sind fundamentale Naturkräfte?',
    ARRAY['Gravity','Electromagnetism','The Strong Nuclear Force'],
    ARRAY['Schwerkraft','Elektromagnetismus','Die Starke Kernkraft'],
    ARRAY['Friction','Tension','Momentum','Inertia','Buoyancy','Torque'],
    ARRAY['Reibung','Spannung','Impuls','Trägheit','Auftrieb','Drehmoment'], 'hard'),

  ('History', 'Geschichte',
    'Which of these countries are commonly cited as never having been colonized by a foreign power?', 'Welche dieser Länder gelten gemeinhin als nie von einer fremden Macht kolonisiert?',
    ARRAY['Japan','Thailand','Ethiopia'],
    ARRAY['Japan','Thailand','Äthiopien'],
    ARRAY['India','Vietnam','Kenya','Brazil','Mexico','Indonesia'],
    ARRAY['Indien','Vietnam','Kenia','Brasilien','Mexiko','Indonesien'], 'hard'),

  ('Movies & TV', 'Filme & TV',
    'Which of these directors are best known for horror films?', 'Welche dieser Regisseure sind vor allem für Horrorfilme bekannt?',
    ARRAY['Wes Craven','John Carpenter','Alfred Hitchcock'],
    ARRAY['Wes Craven','John Carpenter','Alfred Hitchcock'],
    ARRAY['Steven Spielberg','Christopher Nolan','Quentin Tarantino','Martin Scorsese','James Cameron','Ridley Scott'],
    ARRAY['Steven Spielberg','Christopher Nolan','Quentin Tarantino','Martin Scorsese','James Cameron','Ridley Scott'], 'hard'),

  ('Animals', 'Tiere',
    'Which of these birds cannot fly?', 'Welche dieser Vögel können nicht fliegen?',
    ARRAY['Ostrich','Penguin','Kiwi'],
    ARRAY['Strauß','Pinguin','Kiwi'],
    ARRAY['Eagle','Falcon','Hawk','Sparrow','Hummingbird','Peacock'],
    ARRAY['Adler','Falke','Habicht','Spatz','Kolibri','Pfau'], 'hard'),

  ('Science', 'Wissenschaft',
    'Which of these are bones in the human body?', 'Welche davon sind Knochen im menschlichen Körper?',
    ARRAY['Femur','Tibia','Humerus'],
    ARRAY['Oberschenkelknochen','Schienbein','Oberarmknochen'],
    ARRAY['Bicep','Tendon','Cartilage','Ligament','Cornea','Retina'],
    ARRAY['Bizeps','Sehne','Knorpel','Band','Hornhaut','Netzhaut'], 'hard'),

  ('History', 'Geschichte',
    'Which of these were Holy Roman Emperors?', 'Welche davon waren Heilige Römische Kaiser?',
    ARRAY['Charlemagne','Otto I','Frederick Barbarossa'],
    ARRAY['Karl der Große','Otto I.','Friedrich Barbarossa'],
    ARRAY['Napoleon Bonaparte','Louis XIV','Peter the Great','Ivan the Terrible','Charles de Gaulle','Otto von Bismarck'],
    ARRAY['Napoleon Bonaparte','Ludwig XIV.','Peter der Große','Iwan der Schreckliche','Charles de Gaulle','Otto von Bismarck'], 'hard'),

  ('Geography', 'Geografie',
    'Which of these countries span two continents?', 'Welche dieser Länder erstrecken sich über zwei Kontinente?',
    ARRAY['Russia','Turkey','Egypt'],
    ARRAY['Russland','Türkei','Ägypten'],
    ARRAY['France','Germany','China','India','Canada','Brazil'],
    ARRAY['Frankreich','Deutschland','China','Indien','Kanada','Brasilien'], 'hard'),

  ('Music', 'Musik',
    'Which of these composers are from the Baroque era?', 'Welche dieser Komponisten stammen aus der Barockzeit?',
    ARRAY['Johann Sebastian Bach','George Frideric Handel','Antonio Vivaldi'],
    ARRAY['Johann Sebastian Bach','Georg Friedrich Händel','Antonio Vivaldi'],
    ARRAY['Beethoven','Mozart','Chopin','Debussy','Stravinsky','Wagner'],
    ARRAY['Beethoven','Mozart','Chopin','Debussy','Strawinsky','Wagner'], 'hard'),

  ('Mathematics', 'Mathematik',
    'Which of these numbers are prime?', 'Welche dieser Zahlen sind Primzahlen?',
    ARRAY['2','7','13'],
    ARRAY['2','7','13'],
    ARRAY['9','15','21','4','8','12'],
    ARRAY['9','15','21','4','8','12'], 'hard'),

  ('Geography', 'Geografie',
    'Which of these countries have only one time zone?', 'Welche dieser Länder haben nur eine Zeitzone?',
    ARRAY['Germany','Poland','Italy'],
    ARRAY['Deutschland','Polen','Italien'],
    ARRAY['Russia','USA','Australia','Canada','Brazil','Indonesia'],
    ARRAY['Russland','USA','Australien','Kanada','Brasilien','Indonesien'], 'hard'),

  ('Literature', 'Literatur',
    'Which of these plays were written by Sophocles?', 'Welche dieser Theaterstücke wurden von Sophokles geschrieben?',
    ARRAY['Oedipus Rex','Antigone','Electra'],
    ARRAY['König Ödipus','Antigone','Elektra'],
    ARRAY['The Iliad','The Aeneid','Medea','The Frogs','Metamorphoses','The Republic'],
    ARRAY['Ilias','Aeneis','Medea','Die Frösche','Metamorphosen','Der Staat'], 'hard'),

  ('Animals', 'Tiere',
    'Which of these animals are mainly nocturnal?', 'Welche dieser Tiere sind überwiegend nachtaktiv?',
    ARRAY['Owl','Bat','Raccoon'],
    ARRAY['Eule','Fledermaus','Waschbär'],
    ARRAY['Eagle','Squirrel','Rooster','Butterfly','Peacock','Sparrow'],
    ARRAY['Adler','Eichhörnchen','Hahn','Schmetterling','Pfau','Spatz'], 'hard'),

  ('Science', 'Wissenschaft',
    'Which of these are SI base units?', 'Welche davon sind SI-Basiseinheiten?',
    ARRAY['Meter','Kilogram','Second'],
    ARRAY['Meter','Kilogramm','Sekunde'],
    ARRAY['Newton','Watt','Joule','Pascal','Volt','Hertz'],
    ARRAY['Newton','Watt','Joule','Pascal','Volt','Hertz'], 'hard'),

  ('Geography', 'Geografie',
    'Which of these are among the world''s three most populous countries?', 'Welche davon zählen zu den drei bevölkerungsreichsten Ländern der Welt?',
    ARRAY['India','China','USA'],
    ARRAY['Indien','China','USA'],
    ARRAY['Russia','Brazil','Indonesia','Nigeria','Pakistan','Bangladesh'],
    ARRAY['Russland','Brasilien','Indonesien','Nigeria','Pakistan','Bangladesch'], 'hard'),

  ('Movies & TV', 'Filme & TV',
    'Which of these films won the Academy Award for Best Picture?', 'Welche dieser Filme gewannen den Oscar für den besten Film?',
    ARRAY['Parasite','The Godfather','Titanic'],
    ARRAY['Parasite','Der Pate','Titanic'],
    ARRAY['The Dark Knight','Pulp Fiction','Inception','Avatar','Fight Club','The Shawshank Redemption'],
    ARRAY['The Dark Knight','Pulp Fiction','Inception','Avatar','Fight Club','Die Verurteilten'], 'hard'),

  ('Science', 'Wissenschaft',
    'Which of these are layers of the Earth?', 'Welche davon sind Schichten der Erde?',
    ARRAY['Crust','Mantle','Core'],
    ARRAY['Kruste','Mantel','Kern'],
    ARRAY['Troposphere','Stratosphere','Ionosphere','Exosphere','Mesosphere','Thermosphere'],
    ARRAY['Troposphäre','Stratosphäre','Ionosphäre','Exosphäre','Mesosphäre','Thermosphäre'], 'hard'),

  ('History', 'Geschichte',
    'Which of these countries were part of the Axis powers in World War II?', 'Welche dieser Länder gehörten im Zweiten Weltkrieg zu den Achsenmächten?',
    ARRAY['Germany','Japan','Italy'],
    ARRAY['Deutschland','Japan','Italien'],
    ARRAY['Britain','France','Soviet Union','USA','Poland','China'],
    ARRAY['Großbritannien','Frankreich','Sowjetunion','USA','Polen','China'], 'hard'),

  ('Geography', 'Geografie',
    'Which of these seas have no natural connection to the ocean?', 'Welche dieser Meere haben keine natürliche Verbindung zum Ozean?',
    ARRAY['The Caspian Sea','The Dead Sea','The Aral Sea'],
    ARRAY['Das Kaspische Meer','Das Tote Meer','Der Aralsee'],
    ARRAY['The Mediterranean Sea','The Red Sea','The Black Sea','The North Sea','The Baltic Sea','The Adriatic Sea'],
    ARRAY['Das Mittelmeer','Das Rote Meer','Das Schwarze Meer','Die Nordsee','Die Ostsee','Die Adria'], 'hard'),

  ('Animals', 'Tiere',
    'Which of these animals can regrow lost body parts?', 'Welche dieser Tiere können verlorene Körperteile nachwachsen lassen?',
    ARRAY['Starfish','Axolotl','Sea Cucumber'],
    ARRAY['Seestern','Axolotl','Seegurke'],
    ARRAY['Human','Dog','Cat','Elephant','Shark','Cow'],
    ARRAY['Mensch','Hund','Katze','Elefant','Hai','Kuh'], 'hard'),

  ('Science', 'Wissenschaft',
    'Which of these are types of blood cells?', 'Welche davon sind Arten von Blutzellen?',
    ARRAY['Red Blood Cells','White Blood Cells','Platelets'],
    ARRAY['Rote Blutkörperchen','Weiße Blutkörperchen','Blutplättchen'],
    ARRAY['Neurons','Muscle Fibers','Skin Cells','Bone Cells','Fat Cells','Stem Cells'],
    ARRAY['Neuronen','Muskelfasern','Hautzellen','Knochenzellen','Fettzellen','Stammzellen'], 'hard'),

  ('Geography', 'Geografie',
    'Which of these countries have hosted the Summer Olympics more than once?', 'Welche dieser Länder haben die Olympischen Sommerspiele mehr als einmal ausgerichtet?',
    ARRAY['USA','France','United Kingdom'],
    ARRAY['USA','Frankreich','Vereinigtes Königreich'],
    ARRAY['Brazil','China','Russia','Spain','South Korea','Canada'],
    ARRAY['Brasilien','China','Russland','Spanien','Südkorea','Kanada'], 'hard'),

  ('Movies & TV', 'Filme & TV',
    'Which of these actors have won the Academy Award for Best Actor?', 'Welche dieser Schauspieler haben den Oscar als bester Hauptdarsteller gewonnen?',
    ARRAY['Leonardo DiCaprio','Daniel Day-Lewis','Anthony Hopkins'],
    ARRAY['Leonardo DiCaprio','Daniel Day-Lewis','Anthony Hopkins'],
    ARRAY['Tom Cruise','Johnny Depp','Harrison Ford','Samuel L. Jackson','Ryan Gosling','Mark Wahlberg'],
    ARRAY['Tom Cruise','Johnny Depp','Harrison Ford','Samuel L. Jackson','Ryan Gosling','Mark Wahlberg'], 'hard'),

  ('Science', 'Wissenschaft',
    'Which of these chemical elements are named after scientists?', 'Welche dieser chemischen Elemente sind nach Wissenschaftlern benannt?',
    ARRAY['Curium','Einsteinium','Mendelevium'],
    ARRAY['Curium','Einsteinium','Mendelevium'],
    ARRAY['Oxygen','Carbon','Nitrogen','Iron','Gold','Silver'],
    ARRAY['Sauerstoff','Kohlenstoff','Stickstoff','Eisen','Gold','Silber'], 'hard'),

  ('Geography', 'Geografie',
    'Which of these countries drive on the left side of the road?', 'Welche dieser Länder fahren auf der linken Straßenseite?',
    ARRAY['United Kingdom','Japan','Australia'],
    ARRAY['Vereinigtes Königreich','Japan','Australien'],
    ARRAY['Germany','France','USA','Canada','Spain','Italy'],
    ARRAY['Deutschland','Frankreich','USA','Kanada','Spanien','Italien'], 'hard');
